---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Homer"
subtitle: "Sweet HomeLab Dashboard"
logo: "logo.png"
icon: "fas fa-home" # Optional icon

header: true
footer: '<p>Created by Manu Java 2024 Copyright</p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Development Env!"
  icon: "fa fa-grin"
  content: "This is still in development phase."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Whatsapp Me"
    icon: "fab fa-whatsapp"
    url: "https://wa.me/254788109331"
    target: "_blank" # optional html a tag target attribute
  - name: "LinkedIn"
    icon: "fas fa-linked-in"
    url: "https://linkedin.com/in/emmanuel-kirui/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:

############################################################################################################

  - name: "Management Services"
    icon: "fas fa-server"
    items:

      - name: "Proxmox VE"
        logo: "assets/tools/microchip.svg"
        subtitle: "VMs & CTs"
        tag: "venv"
        keywords: "Virtualization Env"
        url: "https://10.176.16.2:8006/"
        target: "_blank" # optional html a tag target attribute


      - name: "Portainer"
        logo: "assets/tools/cube.svg"
        subtitle: "Container Manager"
        tag: "CTs"
        keywords: "self hosted CTs mngr"
        url: "http://10.176.16.7:9000/"
        target: "_blank" # optional html a tag target attribute
       
      - name: "TurnkeyDC"
        logo: "assets/tools/microchip.svg"
        subtitle: "Domain Controller"
        tag: "venv"
        keywords: "DC Mgt"
        url: "https://10.176.16.30:12321/samba"
        target: "_blank" # optional html a tag target attribute

      - name: "Neo4j"
        logo: "assets/tools/database.svg"
        subtitle: "Database Connector"
        tag: "dbconnect"
        keywords: "DB Mgt"
        url: "http://10.176.16.155:7474/browser/"
        target: "_blank" # optional html a tag target attribute

############################################################################################################        

  - name: "Communication"
    icon: "fas fa-phone"
    items:
      - name: "Silverpeas"
        logo: "assets/tools/weixin.svg"
        subtitle: "Self-Hosted Diary"
        tag: "diary"
        keywords: "self hosted diary"
        url: "http://10.176.16.12:8080/silverpeas/"
        target: "_blank" # optional html a tag target attribute
        # EE:D4:7A:F6:64:B9

      - name: "Monica"
        logo: "assets/tools/message.svg"
        subtitle: "Let's Chat"
        tag: "chat_app"
        keywords: "self hosted chat_app"
        url: "http://10.176.16.19:8080/"
        target: "_blank" # optional html a tag target attribute

      - name: "osTicket"
        logo: "assets/tools/weixin.svg"
        subtitle: "Ticketing System"
        tag: "ticket_app"
        keywords: "self hosted ticket_app"
        url: "http://10.176.16.150:8080/"
        target: "_blank" # optional html a tag target attribute

      - name: "Rocket Chat"
        logo: "assets/tools/weixin.svg"
        subtitle: "Rocket_Chat_App"
        tag: "chat_app"
        keywords: "self hosted chat_app"
        url: "http://10.176.16.152:3000/home"
        target: "_blank" # optional html a tag target attribute        

      - name: "Jitsi Meet"
        logo: "assets/tools/tv.svg"
        subtitle: "Video_Conference_App"
        tag: "chat_app"
        keywords: "self hosted vidpe_chat_app"
        url: "https://10.176.16.150/"
        target: "_blank" # optional html a tag target attribute
       
#############################################################################################################
        
  - name: "Micro_Services"
    icon: "fas fa-cloud"
    items:
      
      - name: "HomeAssistant"
        logo: "assets/tools/house-user.svg"
        subtitle: "HomeAssistant Control Panel"
        tag: "home_assistant"
        keywords: "self hosted home"
        url: "http://10.176.16.20:8123/"
        target: "_blank" # optional html a tag target attribute
      

      - name: "TrueNAS"
        logo: "assets/tools/microchip.svg"
        subtitle: "Cloud"
        tag: "cloudstorage"
        keywords: "self hosted store"
        url: "https://10.176.16.10/"
        target: "_blank" # optional html a tag target attribute
        # CA:5C:88:41:23:90

      - name: "Jellyfin"
        logo: "assets/tools/tv.svg"
        subtitle: "Movies,Series & Shows"
        tag: "ent"
        keywords: "self hosted ent"
        url: "https://10.176.16.25:12322/"
        target: "_blank" # optional html a tag target attribute

        


##############################################################################################################
             
  - name: "Network"
    icon: "fas fa-wifi"
    items:

      - name: "Tenda Home"
        logo: "assets/tools/wifi.svg"
        subtitle: "Manage Addresses"
        tag: "net"
        keywords: "self hosted netman"
        url: "http://10.176.16.1/"
        target: "_blank" # optional html a tag target attribute
        # 
        
      - name: "4G_MiFi"
        logo: "assets/tools/wifi.svg"
        subtitle: "ISP"
        tag: "ent"
        keywords: "self hosted ent"
        url: "http://10.63.44.1/"
        target: "_blank" # optional html a tag target attribute
        # 
    
############################################################################################################

  - name: "Databases"
    icon: "fas fa-database"
    items:
      - name: "MySQL"
        logo: "assets/tools/database.svg"
        subtitle: "MySQL DB"
        tag: "db"
        keywords: "self hosted db2"
        url: "http://10.176.16.15:8080/"
        target: "_blank" # optional html a tag target attribute
        # 1A:E9:D8:32:79:A8

      - name: "PostgreSQL"
        logo: "assets/tools/database.svg"
        subtitle: "Postgres_DB"
        tag: "db"
        keywords: "self hosted db"
        url: "http://10.176.16.14/"
        target: "_blank" # optional html a tag target attribute
        # CE:3A:FB:BE:A8:2D

      - name: "InfluxDB"
        logo: "assets/tools/database.svg"
        subtitle: "Influx_DB"
        tag: "db"
        keywords: "self hosted db"
        url: "http://10.176.16.21:8086/"
        target: "_blank" # optional html a tag target attribute
        # 0E:0B:19:8D:13:68

############################################################################################################

  - name: "Security, IAM & Active Directory"
    icon: "fas fa-lock"
    items:

      - name: "Vaultwarden"
        logo: "assets/tools/lock.svg"
        subtitle: "Password Manager"
        tag: "passwdmgr"
        keywords: "self hosted passwdmgr"
        url: "http://10.176.16.16"
        target: "_blank" # optional html a tag target attribute
        

      - name: "Keycloak"
        logo: "assets/tools/address-card.svg"
        subtitle: "Identity & Access Management"
        tag: "iam"
        keywords: "self hosted iam"
        url: "http://10.176.16.17:8080/"
        target: "_blank" # optional html a tag target attribute
        # A6:77:8C:8A:CA:8C

      - name: "OpenLDAP"
        logo: "assets/tools/address-card.svg"
        subtitle: "Open Source Active Directory"
        tag: "ad"
        keywords: "self hosted ad"
        url: "https://10.176.16.22/"
        target: "_blank" # optional html a tag target attribute
        # CE:06:99:62:25:CD

      - name: "pfSense"
        logo: "assets/tools/lock.svg"
        subtitle: "Firewall"
        tag: "ad"
        keywords: "self hosted ufw"
        url: "https://10.176.16.199/"
        target: "_blank" # optional html a tag target attribute

      - name: "pihole"
        logo: "assets/tools/lock.svg"
        subtitle: "AdBlock,DHCP,DNS"
        tag: "ad"
        keywords: "self hosted adblock"
        url: "http://10.176.16.150:83/admin/"
        target: "_blank" # optional html a tag target attribute


############################################################################################################

  - name: "Monitoring & Metric Tools"
    icon: "fas fa-tv"
    items:

      - name: "UptimeKuma"
        logo: "assets/tools/heart-pulse.svg"
        subtitle: "Monitoring Tool"
        tag: "watchman"
        keywords: "self hosted uptime monitor"
        url: "http://10.176.16.5:3001/"
        target: "_blank" # optional html a tag target attribute
        

      - name: "Grafana"
        logo: "assets/tools/heart-pulse.svg"
        subtitle: "Monitoring Metrics"
        tag: "monitor"
        keywords: "self hosted monitor"
        url: "http://10.176.16.6:3000/"
        target: "_blank" # optional html a tag target attribute
        # EA:49:9C:25:F2:0B

      - name: "Prometheus"
        logo: "assets/tools/heart-pulse.svg"
        subtitle: "Monitor Services"
        tag: "monitor2"
        keywords: "self hosted monitor2"
        url: "http://10.176.16.9:9090/"
        target: "_blank" # optional html a tag target attribute  


      - name: "Nagios Core"
        logo: "assets/tools/heart-pulse.svg"
        subtitle: "Monitoring Tool"
        tag: "watchman"
        keywords: "self hosted uptime monitor"
        url: "http://10.176.16.150:8088/"
        target: "_blank" # optional html a tag target attribute
    
       
      - name: "Cadvisor"
        logo: "assets/tools/heart-pulse.svg"
        subtitle: "Monitor System Resources"
        tag: "monitor"
        keywords: "self hosted monitor"
        url: "http://10.176.16.39:8080/containers/"
        target: "_blank" # optional html a tag target attribute
        # 


############################################################################################################

  - name: "Backup Tools"
    icon: "fas fa-cloud"
    items:

      - name: "Duplicati"
        logo: "assets/tools/hard-drive.svg"
        subtitle: "Backup Tool"
        tag: "backup"
        keywords: "self hosted backup"
        url: "http://10.176.16.40:8200/ngax/index.html"
        target: "_blank" # optional html a tag target attribute
        

##############################################################################################################

  - name: "Proxies"
    icon: "fas fa-internet"
    items:
      
     # - name: "Nginx Proxy Manager"
      #  logo: "assets/tools/expeditedssl.svg"
       # subtitle: "NginxProxyManager Control Panel"
       # tag: "nginxpm"
       # keywords: "self hosted pm"
       # url: "http://10.176.16.34/"
       # target: "_blank" # optional html a tag target attribute

      - name: "Traefik"
        logo: "assets/tools/expeditedssl.svg"
        subtitle: "Proxy Manager"
        tag: "proxymgr"
        keywords: "self hosted proxymgr"
        url: "http://10.176.16.13:8080"
        target: "_blank" # optional html a tag target attribute
        
  - name: "Web & Web-Servers"
    icon: "fas fa-internet"
    items:

      - name: "Wordpress"
        logo: "assets/tools/expeditedssl.svg"
        subtitle: "Wordpress"
        tag: "wp"
        keywords: "self hosted webserver"
        url: "http://10.176.16.31:8080/"
        target: "_blank" # optional html a tag target attribute


  - name: "Development Environment"
    icon: "fas fa-internet"
    items:
      
      - name: "Gitlab"
        logo: "assets/tools/expeditedssl.svg"
        subtitle: "Gitlab  Dev_Env"
        tag: "nginxpm"
        keywords: "self hosted dev"
        url: "http://10.176.16.150:8000/"
        target: "_blank" # optional html a tag target attribute

      - name: "Docker_Registry"
        logo: "assets/tools/microchip.svg"
        subtitle: "Docker Registry"
        tag: "reg"
        keywords: "self hosted reg"
        url: "http://10.176.16.108:8080/v2/_catalog"
        target: "_blank" # optional html a tag target attribute

      - name: "Ansible"
        logo: "assets/tools/rectangle-list.svg"
        subtitle: "Automation Platform"
        tag: "automation"
        keywords: "automation_P"
        url: "https://10.176.16.4/"
        target: "_blank" # optional html a tag target attribute
        # CA:68:0E:33:FE:59

      - name: "Kestra"
        logo: "assets/tools/rectangle-list.svg"
        subtitle: "Automation Platform"
        tag: "automation"
        keywords: "automation_P"
        url: "http://10.176.16.18:8080/ui/dashboard"
        target: "_blank" # optional html a tag target attribute
        # EE:0E:96:68:1D:81

      - name: "Jenkins"
        logo: "assets/tools/square-check.svg"
        subtitle: "Code Pipeline"
        tag: "Code PL"
        keywords: "self hosted code pl"
        url: "http://10.176.16.8/"
        target: "_blank" # optional html a tag target attribute 

      - name: "Dockge"
        logo: "assets/tools/microchip.svg"
        subtitle: "Docker CTs"
        tag: "venv"
        keywords: "Container Mgt"
        url: "http://10.176.16.42:5001/"
        target: "_blank" # optional html a tag target attribute

      - name: "Redmine"
        logo: "assets/tools/microchip.svg"
        subtitle: "Project Mgr"
        tag: "venv"
        keywords: "Project Mgt"
        url: "http://10.176.16.101:8088/"
        target: "_blank" # optional html a tag target attribute       


